# Author: Valerie Madsen
# Input results are not followed by time.sleep

# IMPORTS
import sys

import time

# GLOBAL PRINT
global print

# START GAME?
def start_game():
    print("")
    print("Tick...")
    time.sleep(1)
    print("Tick...")
    time.sleep(1)
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(3)
    print("Tock...")
    time.sleep(3)
    print("Goes the clock.")
    time.sleep(2)
    print("You have exactly twenty five minutes until your date arrives.")
    time.sleep(3)
    print("Things have been going really well,")
    time.sleep(2)
    print("and this will be their first time over.")
    time.sleep(2)
    print("You better finish getting ready.")
    time.sleep(2)
    print("")
    start = input("1 - Finish preparing for your date\n2 - Call and cancel instead\n(The choice is yours...)\n")
    if start == "1":
        intro()
    elif start == "2":
        time.sleep(2)
        print("")
        print("Maybe next time...")
        time.sleep(2)
        outro()

# INTRO
def intro():
    time.sleep(2)
    print("")
    print("The living room is already clean and tidy.")
    time.sleep(3)
    print("Your home has been luftened,")
    time.sleep(2)
    print("and when you look in the mirror:")
    time.sleep(2)
    print("you are ready!")
    time.sleep(2)
    print("All that's left is to prepare the refreshments and snacks.")
    time.sleep(3)
    print("What will you offer your date to drink?")
    time.sleep(2)
    print("")
    drink = input("1 - Coffee\n2 - Tea\n3 - Water\n")
    if drink == '1' or drink == '2':
        time.sleep(2)
        print("")
        print("That sounds great,")
    elif drink == '3':
        time.sleep(2)
        print("")
        print("A little boring...")
        time.sleep(2)
        print("but equally so refreshing...")
    time.sleep(2)
    print("and what shall you serve to eat alongside it?")
    time.sleep(2)
    print("")
    snack = input("1 - Cookies\n2 - Pears\n3 - Cheese\n4 - Pickled rat\n5 - Nothing\n")
    if snack == '1' or snack == '2' or snack == '3':
        time.sleep(2)
        print("")
        print("A tasty choice.")
        time.sleep(2)
        snacks_yes()
    elif snack == '4':
        time.sleep(2)
        print("")
        print("Um...")
        time.sleep(2)
        print("That certainly is a choice...")
        time.sleep(2)
        print("Why do you even own that?")
        time.sleep(2)
        print("Let's just hope your date can stomach the tails.")
        time.sleep(3)
        print("Moving on...")
        time.sleep(2)
        snacks_yes()
    elif snack == '5':
        time.sleep(2)
        snacks_no()

# SNACKS YES
def snacks_yes():
    print("")
    print("As you set up the drink and snack options,")
    time.sleep(2)
    print("you suddenly hear a knocking on the door.")
    someone_knocks_snacks_yes()

# SNACKS NO
def snacks_no():
    time.sleep(2)
    print("")
    print("That's right.")
    time.sleep(2)
    print("Can't have your date making a mess of cookie or cheese crumbs,")
    time.sleep(3)
    print("pear juice droplets,")
    time.sleep(2)
    print("or stinky rats.")
    time.sleep(2)
    print("This will be a beverages only kind of event...")
    time.sleep(3)
    print("Your thoughts are interrupted:")
    time.sleep(2)
    print("someone is knocking at the door.")
    someone_knocks_snacks_no()

# SOMEONE KNOCKS
def someone_knocks_snacks_yes():
    time.sleep(2)
    print("")
    print("You glance at your watch.")
    time.sleep(2)
    print("It's far too early for someone to be here yet.")
    time.sleep(3)
    print("In fact, your date isn't supposed to even be here for twenty more minutes...")
    time.sleep(3)
    print("Do you want to answer the door?")
    time.sleep(2)
    answer_door = input("1 - Yes, answer the door\n2 - No, ignore it\n3 - Try to see who it is through the window\n")
    if answer_door == '1':
        time.sleep(2)
        print("")
        print("You hurry to the door,")
        time.sleep(2)
        print("and in your rushing,")
        time.sleep(2)
        print("you bump into the table.")
        time.sleep(2)
        print("and spill some of the snacks onto it.")
        time.sleep(2)
        print("It'll have to wait.")
        time.sleep(2)
        print("You get to the door,")
        time.sleep(2)
        print("turn the knob,")
        time.sleep(2)
        print("and open it.")
        answered_snacks_yes()
    elif answer_door == '2':
        time.sleep(2)
        print("")
        print("You won't answer the door,")
        time.sleep(2)
        print("or check to see who it could be through the window.")
        time.sleep(3)
        print("Suddenly you hear a loud clank,")
        time.sleep(2)
        print("as if a marble were dropped through the letter-slit.")
        time.sleep(3)
        print("You walk over to the door,")
        time.sleep(2)
        print("and lightly bump against the table on the way.")
        time.sleep(3)
        print("You've jostled some of the snacks,")
        time.sleep(2)
        print("but nothing has spilled.")
        not_answered_snacks_yes()
    elif answer_door == '3':
        time.sleep(2)
        print("")
        print("You look through the window,")
        time.sleep(2)
        print("to see only the empty road and autumn trees swaying...")
        time.sleep(3)
        print("You can not make anyone out.")
        time.sleep(2)
        try_again = input('1 - Answer the door\n2 - Ignore whoever it is\n')
        if try_again == '1':
            time.sleep(2)
            print("")
            print("You hurry to the door,")
            time.sleep(2)
            print("and in your rushing,")
            time.sleep(2)
            print("you bump into the table.")
            time.sleep(2)
            print("and spill some of the snacks onto it.")
            time.sleep(2)
            print("It'll have to wait.")
            time.sleep(2)
            print("You get to the door,")
            time.sleep(2)
            print("turn the knob,")
            time.sleep(2)
            print("and open it.")
            answered_snacks_yes()
        elif try_again == '2':
            time.sleep(2)
            print("")
            print("You won't answer the door,")
            time.sleep(2)
            print("or check to see who it could be through the window.")
            time.sleep(3)
            print("Suddenly you hear a loud clank,")
            time.sleep(2)
            print("as if a marble were dropped through the letter-slit.")
            time.sleep(3)
            print("You walk over to the door,")
            time.sleep(2)
            print("and lightly bump against the table on the way.")
            time.sleep(3)
            print("You've jostled some of the snacks,")
            time.sleep(2)
            print("but nothing has spilled.")
            not_answered_snacks_yes()

# SOMEONE KNOCKS SNACKS NO
def someone_knocks_snacks_no():
    time.sleep(2)
    print("")
    print("You glance at your watch.")
    time.sleep(2)
    print("It's far too early for someone to be here yet.")
    time.sleep(3)
    print("In fact, your date isn't supposed to even be here for 20 more minutes...")
    time.sleep(3)
    print("Do you want to answer the door?")
    time.sleep(2)
    answer_door = input("1 - Yes: answer the door\n2 - No: ignore it\n3 - Try to see who it is through the window\n")
    if answer_door == '1':
        time.sleep(2)
        print("")
        print("You hurry to the door,")
        time.sleep(2)
        print("turn the knob,")
        time.sleep(2)
        print("and open it.")
        answered_snacks_no()
    elif answer_door == '2':
        time.sleep(2)
        print("")
        print("You won't answer the door,")
        time.sleep(2)
        print("or check to see who it could be through the window.")
        time.sleep(3)
        print("Suddenly you hear a loud clank,")
        time.sleep(2)
        print("as if a marble were dropped through the letter-slit.")
        time.sleep(3)
        print("You walk over to investigate the noise.")
        not_answered_snacks_no()
    elif answer_door == '3':
        time.sleep(2)
        print("")
        print("You look through the window,")
        time.sleep(2)
        print("to see only the empty road and autumn trees swaying...")
        time.sleep(2)
        print("You can not make anyone out.")
        try_again = input('1 - Answer the door\n2 - Ignore whoever it is')
        if try_again == '1':
            time.sleep(2)
            print("")
            print("You hurry to the door,")
            time.sleep(2)
            print("turn the knob,")
            time.sleep(2)
            print("and open it.")
            answered_snacks_no()
        elif try_again == '2':
            time.sleep(2)
            print("")
            print("You won't answer the door,")
            time.sleep(2)
            print("or check to see who it could be through the window.")
            time.sleep(3)
            print("Suddenly you hear a loud clank,")
            time.sleep(2)
            print("as if a marble were dropped through the letter-slit.")
            time.sleep(3)
            print("You walk over to investigate the noise.")
            not_answered_snacks_no()

# ANSWER THE DOOR?
## ANSWERED
def answered_snacks_yes():
    creature_first_meeting()
    time.sleep(2)
    print("")
    you_say = input('1 - "What the?"\n2 - "Disgusting freak!"\n  *slam the door on the creature*\n3 - No thank you.\n4 - "Okay, let me see what you have."\n')
    if you_say == '1':
        creature_hiss()
        creature_says()
        time.sleep(2)
        print("")
        you_say2 = input('1 - "Disgusting freak!"\n  *slam the door on the creature*\n2 - No thank you.\n3 - "Okay, let me see what you have."\n')
        if you_say2 == '1':
            rude_to_creatue_snacks_yes()
        elif you_say2 == '2':
            creature_leaves()
            good_date_snacks_yes()
        elif you_say2 == '3':
            see_wares_snacks_yes()
    elif you_say == '2':
        rude_to_creatue_snacks_yes()        
    elif you_say == '3':
            creature_leaves()
            good_date_snacks_yes()
    elif you_say == '4':
        see_wares_snacks_yes()

def answered_snacks_no():
    creature_first_meeting()
    time.sleep(2)
    print("")
    you_say = input('1 - "What the?"\n2 - "Disgusting freak!"\n  *slam the door on the creature*\n3 - No thank you.\n4 - "Okay, let me see what you have."\n')
    if you_say == '1':
        creature_hiss()
        creature_says()
        time.sleep(2)
        print("")
        you_say2 = input('1 - "Disgusting freak!"\n  *slam the door on the creature*\n2 - No thank you.\n3 - "Okay, let me see what you have."\n')
        if you_say2 == '1':
            rude_to_creature_snacks_no()
        elif you_say2 == '2':
            print()
            creature_leaves()
            good_date_snacks_no()
        elif you_say2 == '3':
            see_wares_snacks_no()
    elif you_say == '2':
        rude_to_creature_snacks_no()        
    elif you_say == '3':
            creature_leaves()
            good_date_snacks_no()
    elif you_say == '4':
        see_wares_snacks_yes()

## NOT ANSWERED
def not_answered_snacks_yes():
    time.sleep(2)
    print("")
    print("When you get to the door, you find a crumpled up piece of, what almost appears to be, newspaper, yet it has no markings.")
    time.sleep(2)
    investigate = input('Do you want to investigate the mysterious item?\n1 - Yes\n 2 - No\n')
    if investigate == '1':
        time.sleep(2)
        print("")
        print("You open the newspaper-like material")
        time.sleep(2)
        print("and find inside it...")
        time.sleep(2)
        print("a single golden eyeball.")
        time.sleep(2)
        print("It's real.")
        time.sleep(2)
        golden_eye = input("What do you want to do with the golden eyeball?\n1 - Throw it in the garbage\n2 - Put it in a drawer for later\n3 - Eat it\n"
                           "4 - Put it in the snack bowl")
        if golden_eye == '1':
            golden_eye_garbage()
        elif golden_eye == '2':
            golden_eye_drawer()
        elif golden_eye == '3':
            golden_eye_eat()
        elif golden_eye == '4':
            golden_eye_in_snacks()
    elif investigate == '2':
        time.sleep(2)
        print("")
        what_do = input("What do you want to do with it then?\n1 - Throw it in the garbage\n2 - Put it in a drawer for later\n")
        if what_do == '1':
            golden_eye_garbage()
        elif what_do == '2':
            golden_eye_drawer

def not_answered_snacks_no():
    time.sleep(2)
    print("")
    print("When you get to the door, you find a crumpled up piece of, what almost appears to be, newspaper, yet it has no markings.")
    time.sleep(2)
    investigate = input('Do you want to investigate the mysterious item?\n1 - Yes\n 2 - No\n')
    if investigate == '1':
        time.sleep(2)
        print("")
        print("You open the newspaper-like material")
        time.sleep(2)
        print("and find inside it...")
        time.sleep(2)
        print("a single golden eyeball.")
        time.sleep(2)
        print("It's real.")
        time.sleep(2)
        golden_eye = input("What do you want to do with the golden eyeball?\n1 - Throw it in the garbage\n2 - Put it in a drawer for later\n3 - Eat it\n")
        if golden_eye == '1':
            golden_eye_garbage()
        elif golden_eye == '2':
            golden_eye_drawer()
        elif golden_eye == '3':
            golden_eye_eat()
    elif investigate == '2':
        time.sleep(2)
        print("")
        what_do = input("What do you want to do with it then?\n1 - Throw it in the garbage\n2 - Put it in a drawer for later\n")
        if what_do == '1':
            golden_eye_garbage()
        elif what_do == '2':
            golden_eye_drawer

# SEE CREATURE'S WARES
def see_wares_snacks_yes(): 
    creature_shows_wares()
    buy = input('1 - "Yes" (buy an eyeball)\n2 - "No, I am not interested in purchasing an eyeball"\n')
    if buy == '1':
        time.sleep(2)
        print("")
        which_eyeball = input('1 - Buy the purple eyeball\n2 - Buy the green eyeball\n3 - Buy the golden eyeball\n4 - Actually, decline buying an eyeball\n')
        if which_eyeball == '1': # three custom times
            time.sleep(2)
            print("")
            print("You tell the creature that you'd like to buy the purple eyeball.")
            time.sleep(3)
            print("The creature drops the eye into your hand, with the paper wrapping included.")
            time.sleep(3)
            print("You look over the eye's largely dialated pupil,")
            time.sleep(3)
            print("the shimmers of gold throughout the iris,")
            time.sleep(2)
            print("and you notice that it's very heavy.") # heavy
            buy_any_eyeball()
            time.sleep(2)
            eat_hide = input("1 - Shove the eyeball in your pocket\n2 - Quickly eat the eyeball\n3 - Hide the eyeball in the snack bowl\n")
            if eat_hide == '1':
                purple_eye_pocket()
            elif eat_hide == '2':
                purple_eye_eat()
            elif eat_hide == '3':
                purple_eye__in_snacks()
        elif which_eyeball == '2':
            time.sleep(2) # two custom times
            print("")
            print("You tell the creature that you'd like to buy the green eyeball.")
            time.sleep(3)
            print("The creature drops the eye into your hand, with the paper wrapping included.")
            time.sleep(3)
            print("Upon receiving the eyeball,")
            time.sleep(2)
            print("even through the paper wrapping,")
            time.sleep(2)
            print("your palm feels incredibly itchy.")
            buy_any_eyeball()
            time.sleep(2)
            eat_hide = input("1 - Shove the eyeball in your pocket\n2 - Hide the eyeball in the snack bowl\n")
            if eat_hide == '1':
                green_eye_pocket()
            elif eat_hide == '2':
                green_eye_snacks()
        elif which_eyeball == '3': # three custom times
            buy_any_eyeball()
            time.sleep(2)
            print("")
            print("You tell the creature that you'd like to buy the golden eyeball.")
            time.sleep(3)
            print("The creature drops the eye into your hand, with the paper wrapping included.")
            time.sleep(3)
            print("Your hand can feel the warmth of the eyeball through even the paper.")
            time.sleep(3)
            print("The eyeball shimmers like a holographic sunset.")
            time.sleep(2)
            buy_any_eyeball()
            time.sleep(2)
            eat_hide = input("1 - Shove the eyeball in your pocket\n2 - Quickly eat the eyeball\n3 - Hide the eyeball in the snack bowl\n")
            if eat_hide == '1':
                golden_eye_pocket()
            elif eat_hide == '2':
                golden_eye_eat()
            elif eat_hide == '3':
                golden_eye_in_snacks()
        elif which_eyeball == '4':
            creature_leaves()
            good_date_snacks_yes()
    elif buy == '2':
        creature_leaves()
        good_date_snacks_yes()

def see_wares_snacks_no(): 
    creature_shows_wares()
    buy = input('1 - "Yes" (buy an eyeball)\n2 - "No, I am not interested in purchasing an eyeball"\n')
    if buy == '1':
        time.sleep(2)
        print("")
        which_eyeball = input('1 - Buy the purple eyeball\n2 - Buy the green eyeball\n3 - Buy the golden eyeball\n4 - Actually, decline buying an eyeball\n')
        if which_eyeball == '1':
            time.sleep(2) # three custom times
            print("")
            print("You tell the creature that you'd like to buy the purple eyeball.")
            time.sleep(3)
            print("The creature drops the eye into your hand, with the paper wrapping included.")
            time.sleep(3)
            print("You look over the eye's largely dialated pupil,")
            time.sleep(3)
            print("the shimmers of gold throughout the iris,")
            time.sleep(2)
            print("and you notice that it's very heavy.") # heavy
            buy_any_eyeball()
            time.sleep(2)
            eat_hide = input("1 - Shove the eyeball in your pocket\n2 - Quickly eat the eyeball\n")
            if eat_hide == '1':
                purple_eye_pocket()
            elif eat_hide == '2':
                purple_eye_eat()
        elif which_eyeball == '2': # two custom times
            time.sleep(2)
            print("")
            print("You tell the creature that you'd like to buy the green eyeball.")
            time.sleep(3)
            print("The creature drops the eye into your hand, with the paper wrapping included.")
            time.sleep(3)
            print("Upon receiving the eyeball,")
            time.sleep(2)
            print("even through the paper wrapping,")
            time.sleep(2)
            print("your palm feels incredibly itchy.")
            buy_any_eyeball()
            time.sleep(2)
            eat_hide = input("1 - Shove the eyeball in your pocket\n")
            if eat_hide == '1':
                green_eye_pocket()
        elif which_eyeball == '3': # three custom times
            buy_any_eyeball()
            time.sleep(2)
            print("")
            print("You tell the creature that you'd like to buy the golden eyeball.")
            time.sleep(3)
            print("The creature drops the eye into your hand, with the paper wrapping included.")
            time.sleep(3)
            print("Your hand can feel the warmth of the eyeball through even the paper.")
            time.sleep(3)
            print("The eyeball shimmers like a holographic sunset.")
            time.sleep(2)
            buy_any_eyeball()
            time.sleep(2)
            eat_hide = input("1 - Shove the eyeball in your pocket\n2 - Quickly eat the eyeball\n")
            if eat_hide == '1':
                golden_eye_pocket()
            elif eat_hide == '2':
                golden_eye_eat()
        elif which_eyeball == '4':
            creature_leaves()
            good_date_snacks_no()
    elif buy == '2':
        creature_leaves()
        good_date_snacks_no()

def creature_shows_wares():
    time.sleep(2)
    print("")
    print("The creature reveals its wares, three crumpled papers,")
    time.sleep(2)
    print("and upon peeling them open, inside each:")
    time.sleep(2)
    print("a single eyebal")
    time.sleep(2)
    print("as follows):")
    time.sleep(2)
    print("A purple eyeball.")
    time.sleep(2)
    print("A green eyeball.")
    time.sleep(2)
    print("And a golden eyeball.")
    time.sleep(2)
    print("Each specimen is glossy and looks emaculate.")
    time.sleep(3)
    print("You can not tell how these eyeballs were harvested so cleanly,")
    time.sleep(3)
    print("but they are definitively real.")
    time.sleep(2)
    print("The creature cups all three specimens in a single, massive, uncurled paw,")
    time.sleep(2)
    print('"Want?" the creature asks you.')
    time.sleep(2)
    investigate = input("1 - Investigate the eyeballs before making a descision\n2 - You've made up your mind already: give the creature your answer\n")
    if investigate == '1':
        time.sleep(2)
        print("")
        print("The eyeballs look so small in the creature's giant palm.")
        time.sleep(3)
        print("The eyeballs look to be,")
        time.sleep(2)
        print("perhaps harvested from a medium-sized mammal.")
        time.sleep(3)
        print("All of the pupils are round and proportional to the irsis.")
        time.sleep(3)
        print("The purple eyeball is the largest of the three.")
        time.sleep(3)
        print("and has the least unusual sense about it.")
        time.sleep(3)
        print("The golden eyeball is the next largest,")
        time.sleep(3)
        print("and it emits a light yellow glow.")
        time.sleep(3)
        print("The green eyeball looks slightly textured,")
        time.sleep(3)
        print("and its form seems less solid.")
    elif investigate == '2':
        time.sleep(2)
        print("")

# CREATURE BEHAVIORS
def creature_says():
    time.sleep(3)
    print("")
    print("Purrchthissss...")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("eyeball...")

def creature_hiss():
    time.sleep(2)
    print("")
    print("*HISS!!!*")

def creature_first_meeting():
    time.sleep(2)
    print("")
    print("It's some kind of... creature...")
    time.sleep(3)
    print("He...")
    time.sleep(2)
    print("No...")
    time.sleep(2)
    print("It.")
    time.sleep(2)
    print("Yes... It.")
    time.sleep(2)
    print("It looms over you, over ten feet tall,")
    time.sleep(3)
    print("but it's neck and back are hunched so greatly,")
    time.sleep(3)
    print("that you look down at its narrow head,")
    time.sleep(3)
    print("which a cloak drapes over and muddles the shape of.")
    time.sleep(3)
    print("It's face points directly to the floor:")
    time.sleep(3)
    print("not visible.")
    time.sleep(2)
    print("You can't make out its eyes,")
    time.sleep(3)
    print("or the mouth from which its voice croaks out to you:")
    creature_says()

def creature_leaves():
    time.sleep(2)
    print("")
    print("The creature turns and leaves.")
    time.sleep(2)
    print("You watch it shuffle across the street,")
    time.sleep(3)
    print("and slowly descend ")
    time.sleep(2)
    print("- bringing its paws to the floor.")
    time.sleep(3)
    print("The creature collapses its ribcage,")
    time.sleep(3)
    print("and pushes the entirity of its body")
    time.sleep(3)
    print("into the cylindrical water drain built,")
    time.sleep(3)
    print("built into the road,.")
    time.sleep(2)
    print("just across your home.")
    time.sleep(2)
    print("It's body is gulped away...")
    time.sleep(2)
    print("...into the darkness.")
    time.sleep(2)
    print("As you watch, you notice another figure in the distance,")
    time.sleep(3)
    print("walking toward you...")
    time.sleep(2)
    print("Oh!")
    time.sleep(1)
    print("Your date...")
    time.sleep(2)
    print("In half a minute, they've nearly made it to your doorstep, and they wave joyfully to you.")

# ANSWERED (RUDE DECLINE)
def rude_to_creatue_snacks_yes():
    creature_hiss()
    time.sleep(2)
    print("")
    print("The creature turns violently and in one leap traverses across the street.")
    time.sleep(2)
    print("You see it plunge itself into the soil, claws forward, digging with great power.")
    time.sleep(2)
    print("In but a moment...")
    time.sleep(2)
    print("...the creature is simply gone...")
    bad_date_snacks_yes()

def rude_to_creature_snacks_no():
    creature_hiss()
    time.sleep(2)
    print("")
    print("The creature turns violently and in one leap traverses across the street.")
    time.sleep(2)
    print("You see it plunge itself into the soil, claws forward, digging with great power.")
    time.sleep(2)
    print("In but a moment...")
    time.sleep(2)
    print("...the creature is simply gone...")
    bad_date_snacks_no()

# ANSWERED (AND BUY EYEBALL)
## BUY ANY EYEBALL
def buy_any_eyeball():
    time.sleep(2)
    print("")
    print("You suddenly wonder with what you must pay,")
    time.sleep(2)
    print("and look up to ask the creature.")
    time.sleep(2)
    print("but the creature is gone,")
    time.sleep(2)
    print("and as you scan the street, you see something not too far away:")
    time.sleep(3)
    print("your date.")
    time.sleep(2)
    print("Without controling yourself, you quickly jump into your hallway and shut the door before your date sees you.")
    time.sleep(3.5)
    print("The eyeball.")
    time.sleep(2)
    print("KNOCK KNOCK KNOCK")
    time.sleep(2)
    print("The eyeball.")
    time.sleep(2)
    print("Your date is here!!!")
    time.sleep(2)
    print("The eyeball.")
    time.sleep(2)
    print("...what do you do?")

### PURPLE EYEBALL
def purple_eye_pocket():
    time.sleep(2)
    print("")
    print("You push the eyeball deep into your pocket.")
    time.sleep(3)
    print("You let your date inside, and give them a hug,")
    time.sleep(3)
    print("being sure to learn in such a way that they don't squish the eyeball.")
    time.sleep(3)
    print("But the eyeball is heavy, and weighs your pocket down greatly.")
    time.sleep(3)
    print("You invite your date to sit across from you at the table in the living room,")
    time.sleep(3)
    print("and you adjust yourself once more to hide the eyeball.")
    time.sleep(3)
    print("As the two of you begin to talk,")
    time.sleep(3)
    print("you notice that your pocket feels less heavy.")
    time.sleep(3)
    print("You reach your hand into it,")
    time.sleep(2)
    print("revealing nothing.")
    time.sleep(2)
    print("But you hold your social graces,")
    time.sleep(2)
    print("and albeit distractedly,")
    time.sleep(2)
    print("complete your date.")
    time.sleep(2)
    print("Later, once your date has gone,")
    time.sleep(2)
    print("you go to the couch and search every crevice of it for the eyeball.")
    time.sleep(3)
    print("But you don't find it...")
    time.sleep(2)
    print("Nor do you find it under the couch.")
    time.sleep(3)
    print("Or anywhere else at all.")
    time.sleep(2)
    print("Just as the creature did,")
    time.sleep(2)
    print("the eyeball has seemingly vanished...")
    time.sleep(2)
    print("'What if it was worth keeping?'")
    time.sleep(3)
    print("'What good fortunes might it have held for you?'")
    time.sleep(3)
    print("Unfortunately, you will never know.")
    time.sleep(3)
    print("But maybe you should consider yourself lucky.")
    time.sleep(3)
    print("Sometimes there is gain in loss.")
    outro()

def purple_eye_eat():
    time.sleep(2)
    print("")
    print("You shove the eyeball into your mouth and quickly gulp it down.")
    time.sleep(3)
    print("It disappears smoothly down your throat,")
    time.sleep(3)
    print("and you feel its heaviness pull it down to your stomach.")
    time.sleep(3)
    print("Immediately you feel sick,")
    time.sleep(2)
    print("but you put on a brave face and try to enjoy your date anyway.")
    time.sleep(3)
    print("At a point in the date, you realize you've been blacking in and out the entire time.")
    time.sleep(3)
    print("You haven't been present at all,")
    time.sleep(2)
    print("every word your date has spoken you haven't heard.")
    time.sleep(3)
    print("They notice this...")
    time.sleep(2)
    print('"Are you okay?" your date asks.')
    time.sleep(2)
    print("You can't find the words to answer that,")
    time.sleep(3)
    print("and you begin to sink deeper into the couch.")
    time.sleep(3)
    print("You sink and sink and sink...")
    time.sleep(2)
    print("It seems to never stop.")
    time.sleep(2)
    print("You wake in a hospital,")
    time.sleep(3)
    print("it seems like a hospital anyway...")
    time.sleep(3)
    print("But the room is very dimly lit,")
    time.sleep(3)
    print("and there are no windows.")
    time.sleep(3)
    print("You can not rise from the bed.")
    time.sleep(3)
    print("You can not move at all.")
    time.sleep(3)
    print("And in that bed,")
    time.sleep(2)
    print("in that room,")
    time.sleep(2)
    print("is where you remain furthermore:")
    time.sleep(3)
    print("never knowing how you got there,")
    time.sleep(3)
    print("never knowing where there is at all...")
    time.sleep(3)
    print("never falling to sleep...")
    time.sleep(3)
    print("never waking...")
    time.sleep(2)
    print("and never,")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("...leaving.")
    outro()

def purple_eye__in_snacks():
    eye_in_snacks()
    time.sleep(2)
    print("")
    print("Your date's face squiggles into an expression of abject disgust and horror.")
    time.sleep(3)
    print("They begin to spit out what they've just consumed,")
    time.sleep(3)
    print("their tongue scraping against their teeth and trying to fling every flake out.")
    time.sleep(3)
    print("But then they fall to the floor,")
    time.sleep(3)
    print("and begin to convulse violently.")
    time.sleep(3)
    print("What have you done?!...")
    time.sleep(2)
    call = input('Do you call the police for help?\n1 - Yes\n2 - No\n')
    if call == '1': 
        time.sleep(2)
        print("")
        print("You dial 9-1-1")
        time.sleep(2)
        print('"9-1-1, What is your emergency?"')
        time.sleep(2)
        truth = input('Do you tell the full truth, including the eyeball?\n Or give a partial truth instead?\n1 - Give full truth\n2 - Give partial truth')
        if truth == '1': # custom times
            time.sleep(2)
            print("")
            print("You explain everything - including the eyeball and the mysterious creature.")
            time.sleep(3)
            print("Within minutes the police and EMS arrive.")
            psycho_ending()   
        elif truth == '2': # custom times
            time.sleep(2)
            print("")
            print("Within minutes the police and EMS arrive.")
            time.sleep(3)
            print("They take your date away")
            time.sleep(2)
            print("and ask you some questions about what happened.")
            time.sleep(3)
            print("You repeat your story, with the partial truth, just as you did over the phone.")
            time.sleep(3)
            print("You have your reasons.")
            time.sleep(2)
            print("The next day you try to find out what happened to your date.")
            time.sleep(3)
            print("You first try to contact them everyway you can think to,")
            time.sleep(3)
            print("but they do not reply anywhere.")
            time.sleep(3)
            print("You even try calling, and then visiting, the hospital,")
            time.sleep(3)
            print("There is no record that they were ever there.")
            time.sleep(3)
            print("You reach out to everyone on their social media,")
            time.sleep(3)
            print("Everyone and anyone who could know what happened to them")
            time.sleep(3)
            print("- what kind of state they are in...")
            time.sleep(3)
            print("But nobody knows where they went.")
            time.sleep(3)
            print("And nobody ever will...")
            outro()
    elif call == '2':
        time.sleep(2)
        print("")
        print("You watch your date squirm until...")
        time.sleep(3)
        print("in one final violent thrash,")
        time.sleep(3)
        print("they die.")
        time.sleep(2)
        rid_body = input("1 - Call the police\n2 - Bury your date in the backyard\n")
        if rid_body == '1':
                time.sleep(2)
                print("")
                print("You dial 9-1-1")
                time.sleep(2)
                print('"9-1-1, What is your emergency?"')
                time.sleep(2)
                truth = input('Do you tell the full truth, including the eyeball?\n Or give a partial truth instead?\n1 - Give full truth\n2 - Give partial truth')
                if truth == '1':
                    time.sleep(2)
                    print("")
                    print("You explain everything - including the eyeball and the mysterious creature.")
                    time.sleep(3)
                    print("Within minutes the police and EMS arrive.")
                    psycho_ending()   
                elif truth == '2':
                    time.sleep(2)
                    print("")
                    print("Within minutes the police and EMS arrive.")
                    time.sleep(3)
                    print("They take your date away")
                    time.sleep(3)
                    print("and ask you some questions about what happened.")
                    time.sleep(3)
                    print("You repeat your story, with the partial truth, just as you did over the phone.")
                    time.sleep(3)
                    print("You have your reasons.")
                    time.sleep(2)
                    print("And when you try to find out what happened to your date,")
                    time.sleep(3)
                    print("why they died, and 'how' according to any autospy report,")
                    time.sleep(3)
                    print("you can find nothing.")
                    time.sleep(2)
                    print("Perhaps in part because nobody knows -")
                    time.sleep(3)
                    print("perhaps the truth about the eyeball would have helped,")
                    time.sleep(3)
                    print("but alas...")
                    time.sleep(2)
                    print("And what of the creature?")
                    time.sleep(3)
                    print("It never knocks on your door again...")
                    time.sleep(3)
                    print("But sometimes,")
                    time.sleep(2)
                    print("in the blurriest part of a reflection,")
                    time.sleep(3)
                    print("or in the darkness of the drain across the street,")
                    time.sleep(3)
                    print("(and in fact, in the drain of any street)")
                    time.sleep(3)
                    print("you think you see it...")
                    time.sleep(2)
                    print("watching...")
                    time.sleep(2)
                    print("you.")
                    outro()

        elif rid_body == '2':
            time.sleep(2)
            print("")
            print("You bury your date in the backyard.")
            time.sleep(3)
            print("In this process,")
            time.sleep(2)
            print("you're surprised by two things;")
            time.sleep(3)
            print("- how physically toiling burying a body is")
            time.sleep(3)
            print("- how easy it is to get away with a murder.")
            time.sleep(3)
            print("The police come and they question you...")
            time.sleep(3)
            print("but you're not the kind of person who does *that kind of thing.*")
            time.sleep(3)
            print("Not in their eyes anyway...")
            time.sleep(3)
            print("You're not the kind of person who hides an entire human corpse in their backyard...")
            time.sleep(3)
            print("and on top of that,")
            time.sleep(3)
            print("you're friendly.")
            time.sleep(2)
            print("You're sociable.")
            time.sleep(2)
            print("The police appreciate your cooperation,")
            time.sleep(3)
            print("and shift the investigatory focus away from you.")
            time.sleep(3)
            print("")
            print("The years go by,")
            time.sleep(2)
            print("and the case is unable to close.")
            time.sleep(3)
            print("It simply halts -")
            time.sleep(2)
            print("'A person gone missing' a typical tale...")
            time.sleep(3)
            print('"It was probably a suicide," people who knew your date would say,')
            time.sleep(3)
            print('"They struggled with depression after all..."')
            time.sleep(3)
            print("Besides the weight on your concious,")
            time.sleep(3)
            print("there is another problem which haunts you over the years as a result of this event:")
            time.sleep(3)
            print("You can not sell the house.")
            time.sleep(3)
            print("The body could be uncovered, and so,")
            time.sleep(3)
            print("here you must remain until the end of your days.")
            time.sleep(3)
            print("And before you think that's the problem,")
            time.sleep(3)
            print("let me assure you that it is actually much deeper than that:")
            time.sleep(3)
            print("For every night,")
            time.sleep(2)
            print("a soft knocking awakens you...")
            time.sleep(3)
            print("a knocking on your door which produces no visitor.")
            time.sleep(3)
            print("And when you look out your window,")
            time.sleep(3)
            print("you see it...")
            time.sleep(2)
            print("at the furthest end of the street,")
            time.sleep(3)
            print("never reachable no matter how fast you sprint,")
            time.sleep(3)
            print("never visible to anyone else...")
            time.sleep(3)
            print("there stands the creature.")
            outro()

# GREEN EYEBALL
def green_eye_snacks():
    time.sleep(2)
    print("")
    print("As quickly as you can, you arrange the snacks to cover and hide the eyeball.")
    time.sleep(3)
    print("You let your date in, and they greet you with a hug.")
    time.sleep(3)
    print("Together you sit at the couch, and enjoy your drinks and the food you've arranged.")
    time.sleep(3)
    print("You see their hand digging into the snack bowl,")
    time.sleep(2)
    print("and you lock eyes intensely with them,")
    time.sleep(2)
    print("hoping to keep their gaze.")
    time.sleep(2)
    print("The eyeball is in their hand,")
    time.sleep(2)
    print("and they let out a shriek.")
    time.sleep(2)
    print('"My hand!" they cry out, itching it without mercy.')
    time.sleep(3)
    print("You apologize - and it's genuine.")
    time.sleep(3)
    print("You run over to them, and knowing better now,")
    time.sleep(3)
    print("from your first 'touching of the green eyeball',")
    time.sleep(3)
    print("you kick the eye away from them.")
    time.sleep(3)
    print("Luckily they did not see what it was...")
    time.sleep(3)
    print("Your date is on the floor, ravenously scratching at their hand,")
    time.sleep(3)
    print('"I will get you something! Just one moment!" you tell them')
    time.sleep(3)
    print("but they do not acknowledge you or look over at all.")
    time.sleep(3)
    print("They only itch.")
    time.sleep(2)
    print("Upon returning to the room,")
    time.sleep(3)
    print("you date is still sitting on the floor,")
    time.sleep(3)
    print("and they are gnawing themself, with their hand fully immersed in their mouth.")
    time.sleep(3)
    print("Blood trickles down their chin and soaks their shirt and the floor below them.")
    time.sleep(3)
    print("You slide across the room to them")
    time.sleep(3)
    print("grabbing their arm and pulling it from their mouth.")
    time.sleep(3)
    print("A stub remains...")
    outro()

def green_eye_pocket():
    time.sleep(2)
    print("")
    print("You shove the eyeball into your right pocket,")
    time.sleep(3)
    print("and go to the door, greet your date, and invite them in.")
    time.sleep(3)
    print("The two of you sit at the couch,")
    time.sleep(3)
    print("and your date takes their drink in hand, and begins recounting their day to you.")
    time.sleep(3)
    print("But you can not concentrate...")
    time.sleep(3)
    print("you feel anxious and you look to your watch.")
    time.sleep(3)
    print("A persistent discomfort,")
    time.sleep(3)
    print("a low-level torment,")
    time.sleep(2)
    print("gnaws at your focus.")
    time.sleep(2)
    print("It steals your peace of mind.")
    time.sleep(3)
    print("The insistent urge to scratch your leg,")
    time.sleep(2)
    print("where the eyeball waits,") 
    time.sleep(2)
    print("intensifies the more you resist it.")
    time.sleep(2)
    print("A low-level torment begins to pull more deeply into the strings of your mind...")
    time.sleep(3)
    print("")
    print("Your date pauses what they are saying,")
    time.sleep(3)
    print("and they look directly at you.")
    time.sleep(3)
    print('"Is everything okay?" they ask you.')
    time.sleep(2)
    pocket_response = input("1 - Remove the eyeball from your pocket\n2 - Itch the eyeball through your pants\n")
    if pocket_response == '1':
        green_eye_pocket_remove()
    elif pocket_response == '2':
        green_eye_pocket_itch()

def green_eye_pocket_remove():
    time.sleep(2)
    print("")
    print("You remove the eyeball from your pocket,")
    time.sleep(3)
    print("Your hand, the same in which you first held it,")
    time.sleep(3)
    print("now burns with an immense irritation.")
    time.sleep(3)
    print("You can not contain yourself:")
    time.sleep(3)
    print("You let out a yelp and drop the eyeball to the ground.")
    time.sleep(3)
    print("For a moment, your date lends you a puzzled expression,")
    time.sleep(3)
    print("as if they are offering you the benefit of the doubt,")
    time.sleep(3)
    print("but within moments the truth is undeniable:")
    time.sleep(3)
    print("that is a genuine eyeball.")
    time.sleep(3)
    print("An eyeball just came out...")
    time.sleep(3)
    print("of...")
    time.sleep(3)
    print("your pocket...")
    time.sleep(3)
    print("Your date looks incredibly uncomfortable.")
    time.sleep(3)
    print('"Actually, I am so, so sorry,"')
    time.sleep(3)
    print("Your date is already gathering their things, and rising to leave as they continue,")
    time.sleep(3)
    print('"I think I have to go..."')
    time.sleep(2)
    print("They dash out the front door.")
    time.sleep(3)
    print("")
    print("Before you can say anything,")
    time.sleep(3)
    print("You are crippled by the intense urge to itch your hand,")
    time.sleep(3)
    print("your leg,")
    time.sleep(2)
    print("now the whole right side of your body.")
    time.sleep(2)
    print("You fall to the ground itching and itching yourself.")
    time.sleep(3)
    print("Your date is already gone...")
    time.sleep(3)
    print("The door slowly closes before you.")
    time.sleep(3)
    print("Even your throat itches to a point in which you can not utter a word.")
    time.sleep(3)
    print("You scratch at your skin and body,")
    time.sleep(3)
    print("and do not stop...")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("...CAN...")
    time.sleep(2)
    print("not stop.")
    print("...")
    time.sleep(2)
    print("They don't find you for almost a week.")
    time.sleep(3)
    print("But the medical service team-members will never forget how they found you...")
    time.sleep(3)
    print("Raw.")
    time.sleep(3)
    print("Without skin.")
    time.sleep(3)
    print('"Scratched themself clean to the bone...')
    outro()

def green_eye_pocket_itch():
    time.sleep(2)
    print("")
    print("You scratch at the eyeball through your pants,")
    time.sleep(3)
    print("and suddenly a disgusting slime melts into the fabric and oozes over your leg.")
    time.sleep(3)
    print('"Ah!!!" yelps out your date.')
    time.sleep(3)
    print("You look down and your leg is splattered in a green goo.")
    time.sleep(3)
    print("Reaching your hand into your pocket,")
    time.sleep(3)
    print("the eyeball has been completely destroyed.")
    time.sleep(3)
    print("It hadn't appeared that it would be so fragile.")
    time.sleep(3)
    print("You excuse yourself,")
    time.sleep(3)
    print("and rush to the bathroom to clean yourself up.")
    time.sleep(3)
    print("Your leg and hand have ceased to itch,")
    time.sleep(3)
    print("and you gather yourself,")
    time.sleep(3)
    print("change your outfit,")
    time.sleep(3)
    print("and head back downstairs.")
    time.sleep(3)
    print("Things are a little awkward at first,")
    time.sleep(3)
    print("You make a joke to your date about how itchy your hand was holding onto some weird 'berry' you had found earlier,")
    time.sleep(3)
    print("and how you put it into your pocket as a result earlier, and had forgotten.")
    time.sleep(3)
    print('Your date looks confused, "Ishy?" they ask.')
    time.sleep(3)
    print("You correct them - it is: 'Itchy'")
    time.sleep(3)
    print("They don't know the word.")
    time.sleep(3)
    print("You try to explain it to them via its definition,")
    time.sleep(3)
    print("and your date begins to laugh.")
    time.sleep(3)
    print('"I really do not understand what you mean," they say.')
    time.sleep(3)
    print("Your date finds the whole concept hilarious,")
    time.sleep(3)
    print("as you try to explain it further,")
    time.sleep(3)
    print("you only make them giggle more.")
    time.sleep(3)
    print("Eventually you drop the topic and the two of you move on to other things.")
    time.sleep(3)
    print("A few days after your date,")
    time.sleep(3)
    print("in which you have been pondering on the strange creature who sold you the green eyeball,")
    time.sleep(3)
    print("whom you have found no traces of,")
    time.sleep(2)
    print("neither on or offline,")
    time.sleep(2)
    print("you notice what appears to be a mosquito bite on your arm.")
    time.sleep(3)
    print("But it does not itch at all.")
    time.sleep(2)
    print("Not even when you purposefully irritate it.")
    time.sleep(3)
    print("And some time later,")
    time.sleep(2)
    print("you realize that it's been a great deal of time since you last felt the sensation of being itchy.")
    time.sleep(3)
    print("A sensation that no one else,")
    time.sleep(3)
    print("even people besides your date,")
    time.sleep(3)
    print("seem to comprehend.")
    time.sleep(2)
    print("Not even the internet.")
    time.sleep(2)
    print("Nor any book or historical record you ever search.")
    time.sleep(3)
    print("You are the only one who knows of this sensation.")
    time.sleep(3)
    print("The only one who remembers it...")
    time.sleep(3)
    print("It is like a color unseen; unimaginable, and indescribable to those who do not know of it.")
    time.sleep(3)
    print("And once unimaginable to you...")
    time.sleep(3)
    print("You find yourself eventually wishing...")
    time.sleep(3)
    print("that you could feel itchy.")
    time.sleep(2)
    print("Just one more time.")
    outro()

# NOT ANSWERED
## GOLDEN EYEBALL 
def golden_eye_garbage():
    time.sleep(2)
    print("")
    print("You throw the golden eyeball into the garbage and rearrange some of the other waste to cover it.")
    time.sleep(3)
    print("Just as you finish, you hear knocking on your door again.")
    time.sleep(3)
    print("You look at your watch and based on the time, it must be your date.")
    time.sleep(3)
    print("You open the door, invite your date in, and sit together at the couch and have a pleasant time.")
    time.sleep(3)
    print("Later that evening, you feel uneasy as you remember the golden eyeball")
    time.sleep(3)
    print("You head down to the kitchen and dig through the garbage basket,")
    time.sleep(3)
    print("but you can not find the it anywhere.")
    time.sleep(3)
    print("A soft voice speaks from the other room,")
    time.sleep(3)    
    print("you pause and listen to it.")
    time.sleep(3)
    print("You follow the noise and find your television on,")
    time.sleep(3)
    print("and a broadcaster narrates alongside horrific footage,")
    time.sleep(3)
    print("unlike any you have ever seen before...")
    time.sleep(3)
    print("A terrible train derailment.")
    time.sleep(3)
    print("Bodies everywhere.")
    time.sleep(3)
    print("The camera pans to the pools of blood")
    time.sleep(3)
    print("and to the mangled skin that has become enmeshed into the seats and metal of the twisted metal of the train.")
    time.sleep(3)
    print("Most likely realizing their need to tread lightly,")
    time.sleep(3)
    print("lest the broadcast be ended,")
    time.sleep(3)
    print("the image cuts to the studio,")
    time.sleep(3)
    print("where cast to the side of the broadcaster are the photos of victims of the train wreck.")
    time.sleep(3)
    print("You see your date's face.")
    time.sleep(3)
    print("And you see, blurring in and out of focus atop your date's face, another face.")
    time.sleep(3)
    print("It is a reflection.")
    time.sleep(3)
    print("But not your own.")
    time.sleep(3)
    print("A dark figure is hunched behind you.")
    time.sleep(3)
    print("You can not make out its form,")
    time.sleep(3)
    print("Save for that it is immensely large,")
    time.sleep(3)
    print("and shrouded in a long cloak.")
    time.sleep(3)
    print("The creature's mouth opens, like a smile,")
    time.sleep(3)
    print("and a thousand needled teeth smile at you.")
    time.sleep(3)
    print("*HISSSSHTLLKLKTJLKTJTKTJTJTJTTKLT")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("...")
    outro()

def golden_eye_drawer():
    time.sleep(2)
    print("")
    print("In your kitchen, you pull open a drawer,")
    time.sleep(2)
    print("you move aside the knick-knacks and papers which crowd it, and place the golden eye into it.")
    time.sleep(3)
    print("Just as you finish, you hear knocking on your door again.")
    time.sleep(3)
    print("You look at your watch and based on the time, it must be your date.")
    time.sleep(3)
    print("As you close the drawer, you hear the eyeball rolling back into its depths.")
    time.sleep(3)
    print("You open the door and invite your date in.")
    time.sleep(3)
    print("Together you enjoy the time spent together,")
    time.sleep(3)
    print("and come the end of your time together,")
    time.sleep(3)
    print("you part with a hug and good feelings.")
    time.sleep(3)
    print("Later that evening, you are snuggled deep into your pillows and blankets,")
    time.sleep(3)
    print("drifting into a cozy warm dream,")
    time.sleep(3)
    print("when you remember the strange golden eyeball,")
    time.sleep(3)
    print("and the creature which brought you it.")
    time.sleep(3)
    print("You head down to the kitchen and dig through the drawer,")
    time.sleep(3)
    print("but you can not find the it anywhere,")
    time.sleep(3)
    print("even when you take the drawer out and dump its contents to the floor.")
    time.sleep(3)
    print("You return to your bed,")
    time.sleep(3)
    print("close your eyes,")
    time.sleep(2)
    print("and drift...")
    time.sleep(2)
    print("into...")
    time.sleep(2)
    print("a...")
    time.sleep(2)
    print("warm sleep...")
    time.sleep(2)
    print("You wake to knocking at your door,")
    time.sleep(3)
    print("and you glance at your watch.")
    time.sleep(3)
    print("It's far too early for someone to be here yet.")
    time.sleep(3)
    print("In fact, your date isn't supposed to even be here for twenty more minutes...")
    outro()

def golden_eye_eat():
    time.sleep(2)
    print("")
    print("You look over the perfectly round, golden orb, smooth to the touch,")
    time.sleep(3)
    print("It resembles a miniature sun.")
    time.sleep(3)
    print("As you gaze upon it, you're drawn in by it's warm, inviting glow,")
    time.sleep(3)
    print("Upon taking a bite, the orb yields to your teeth,")
    time.sleep(3)
    print("revealing a bursting, creamy interior which melts through your mouth.")
    time.sleep(3)
    print("The taste is exquisite.")
    time.sleep(3)
    print("The flavors are like sweet passionfruit, delicate honeysuckle, and vibrant mango,")
    time.sleep(3)
    print("fusing together in a symphony of sweetness that lingers long after you swallow the eyeball.")
    time.sleep(3)
    print("It is the most exquisitive thing you've ever experienced.")
    time.sleep(3)
    print("You go over to and rest on the couch,")
    time.sleep(3)
    print("and lay there,")
    time.sleep(2)
    print("in a state you have never experienced before:")
    time.sleep(3)
    print("Euphoria but in calmness.")
    time.sleep(3)
    print("An exquisitve pleasure was the eyeball to consume.")
    time.sleep(3)
    print("A short while later, your date knocks at the door.")
    time.sleep(3)
    print("You invite them in, and together sit,")
    time.sleep(3)
    print("Your focus is sharp,")
    time.sleep(3)
    print("You are charming,")
    time.sleep(3)
    print("delightful,")
    time.sleep(3)
    print("clever.")
    time.sleep(3)
    print("After your date leaves that evening,")
    time.sleep(3)
    print("You go upstairs and sit down at your desk.")
    time.sleep(3)
    print("You feel invigorated,")
    time.sleep(2)
    print("clear minded,")
    time.sleep(2)
    print("and focused like never before.")
    time.sleep(3)
    print("You sit down and begin to write,")
    time.sleep(3)
    print("and by morning you've written a synopsis.")
    time.sleep(3)
    print("By mid-day you've sent it to 5 publishing houses.")
    time.sleep(3)
    print("And by the fortnight, you've sent it to 14 more, and heard back from 13 of them:")
    time.sleep(3)
    print("offers are at hand.")
    time.sleep(2)
    print("The seasons go by, and so does a flurry of excitement:")
    time.sleep(3)
    print("- the first draft")
    time.sleep(2)
    print("- the final draft")
    time.sleep(2)
    print("- book signings")
    time.sleep(2)
    print("- a movie deal")
    time.sleep(2)
    print("but all this time,")
    time.sleep(2)
    print("never do you again find another of the golden eyeball.")
    time.sleep(3)
    print("")
    print("For years,")
    time.sleep(3)
    print("you are sure that, at the least,")
    time.sleep(3)
    print("it's pair must be out there somewhere.")
    time.sleep(3)
    print("This...")
    time.sleep(2)
    print("entire time...")
    time.sleep(2)
    print("its flavor...")
    time.sleep(2)
    print("eludes you...")
    time.sleep(2)
    print("stirs you...")
    time.sleep(2)
    print("haunts you...")
    outro()

def golden_eye_in_snacks():
    eye_in_snacks()
    time.sleep(2)
    print("")
    print("Your date stops mid-sentence with a shocked look upon their face.")
    time.sleep(3)
    print("But then they smile delightfully.")
    time.sleep(3)
    print('"Wow..."')
    time.sleep(2)
    print("You shrink yourself into the couch, the eyeb-")
    time.sleep(3)
    print('"These are DELICIOUS," says your date.')
    time.sleep(3)
    print("Before you can respnd, your date gets up excitedly from their seat.")
    time.sleep(3)
    print("They're manic on a level you've never seen.")
    time.sleep(3)
    print('"Thank you so much for having me!" they say, giving you a kiss on the cheek,')
    time.sleep(3)
    print("They grab their things and as they run out the door, yell back to you,")
    time.sleep(3)
    print('"Thank you so much for having me!"')
    time.sleep(3)
    print("And then they're gone...")
    time.sleep(2)
    print("You pace worridly in your living room,")
    time.sleep(3)
    print("and finally, an hour since you've left, you text them:")
    time.sleep(3)
    print("'Is everything alright?' you write.")
    time.sleep(3)
    print("But you don't hear back that night,")
    time.sleep(3)
    print("actually, you never hear back from them again.")
    time.sleep(3)
    print("Its okay really - things were only at the beginning.")
    time.sleep(3)
    print("")
    print("Years pass by,")
    time.sleep(2)
    print("and one day...")
    time.sleep(2)
    print("you are at the bookstore, and you see a famliar face and name:")
    time.sleep(3)
    print("On the Eloquence of a Reality of Worms")
    time.sleep(3)
    print("Written by your date from all those years ago!")
    time.sleep(3)
    look_around = input('Do you want to look at the other people in the bookstore?\n1 - Yes\n2 - No')
    if look_around == '1':
        time.sleep(2)
        print("")
        print("You look around the shop hurridly,")
        time.sleep(2)
        print("perhaps hoping to see them?")
        time.sleep(2)
        print("You don't find what you were searching for")
        time.sleep(3)
        print("But nearly everyone is carrying a copy of that very book.")
        time.sleep(3)
        book_shop_ending()

    elif look_around == '2':
        book_shop_ending()

def book_shop_ending():
        time.sleep(2)
        print("")
        print("You're a bit surprised,")
        time.sleep(2)
        print("they never really seemed the type to write a book.")
        time.sleep(3)
        print("And with that,")
        time.sleep(2)
        print("you leave the shop and head to work.")
        outro()

def golden_eye_pocket():
    time.sleep(2)
    print("")
    print("You slip the golden eyeball into your pocket,")
    time.sleep(3)
    print("and you hear knocking on your door once more.")
    time.sleep(3)
    print("You look at your watch and based on the time, it must be your date.")
    time.sleep(3)
    print("You open the door and invite your date in.")
    time.sleep(3)
    print("You sit together at the couch and your eyes dart quickly over your pant's pocket,")
    time.sleep(3)
    print("but the eyeball's form is not discernable, and you can relax a little.")
    time.sleep(3)
    print("Your date goes well,")
    time.sleep(2)
    print("and come the end of your time together,")
    time.sleep(3)
    print("you part with a hug and good feelings.")
    time.sleep(3)
    print("Though you are careful to hug them in such a way that they will not press up against the eyeball.")
    time.sleep(3)
    print("As soon as they leave,")
    time.sleep(2)
    print("you plunge your hand into your pocket - but the eyeball is gone.")
    time.sleep(3)
    print("You search over the couch,")
    time.sleep(3)
    print("then deep into the cushions,")
    time.sleep(3)
    print("and everywhere in the living room...")
    time.sleep(3)
    print("but you do not find the eyeball.")
    time.sleep(3)
    print("You go out to the drain which the creature disappeared into,")
    time.sleep(3)
    print("and shining your flashlight into the darkness you see:")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("nothing.")
    time.sleep(2)
    print("Only water flowing and leaves caught up in its pull.")
    time.sleep(3)
    print("You retreat to your room and lay in bed,")
    time.sleep(3)
    print("rising now and then to peak out the blinds for the creature,")
    time.sleep(3)
    print("but... nothingness.")
    time.sleep(2)
    print("Your eyes...")
    time.sleep(2)
    print("you close...")
    time.sleep(2)
    print("CrrrEaTTTuRReee")
    time.sleep(2)
    print("Your mind...")
    time.sleep(2)
    print("drifiting...")
    time.sleep(2)
    print("You...")
    time.sleep(2)
    print("close your eyes,")
    time.sleep(2)
    print("and drift...")
    time.sleep(2)
    print("into...")
    time.sleep(2)
    print("a...")
    time.sleep(2)
    print("warm sleep...")
    time.sleep(2)
    print("You wake to knocking at your door,")
    time.sleep(2)
    print("and you glance at your watch.")
    time.sleep(2)
    print("It's far too early for someone to be here yet.")
    time.sleep(2)
    print("In fact, your date isn't supposed to even be here for twenty more minutes...")
    outro()

# EYE IN SNACKS
def eye_in_snacks():
    time.sleep(2)
    print("")
    print("As quickly as you can, you arrange the snacks to cover and hide the eyeball.")
    time.sleep(3)
    print("You let your date in, and they greet you with a hug.")
    time.sleep(3)
    print("Together you sit at the couch, and enjoy your drinks and the food you've arranged.")
    time.sleep(3)
    print("You see their hand digging into the snack bowl,")
    time.sleep(3)
    print("and you lock eyes intensely with them,")
    time.sleep(3)
    print("hoping to keep their gaze.")
    time.sleep(3)
    print("The eyeball is in their hand,")
    time.sleep(3)
    print("and then you see that hand go to their mouth...")
    time.sleep(3)
    print("and in goes the eyeball...")

# DATE OUTCOMES
def good_date_snacks_yes():
    time.sleep(2)
    print("")
    print("Your date goes...")
    time.sleep(2)
    print("surprisingly quite well!")
    time.sleep(2)
    print("You don't let off that anything strange transpired so soon before their arrival.")
    time.sleep(3)
    print("Together you both enjoy the drinks and snacks you laid out.")
    time.sleep(3)
    print('"Hah," your date smiles as they reach into the bowl,')
    time.sleep(2)
    print('"these are actually my favorite!')
    time.sleep(3)
    print('"How did you know?!"')
    good_date_ending()

def good_date_snacks_no():
    time.sleep(2)
    print("")
    print("Your date goes...")
    time.sleep(2)
    print("surprisingly quite well!")
    time.sleep(3)
    print("You don't let off that anything strange transpired so soon before their arrival.")
    time.sleep(3)
    print('"Thanks for having me over," your date says to you, smiling.')
    time.sleep(3)
    good_date_ending()

def good_date_ending():
    time.sleep(2)
    print("")
    print("You smile back, but before you can reply,")
    time.sleep(3)
    print("you feel a little uneasy.")
    time.sleep(3)
    print("What if the creature returns?")
    time.sleep(3)
    print("What did it come to your home?")
    time.sleep(3)
    print("You turn your attention back to your date.")
    time.sleep(3)
    print('"Is something wrong?" they ask.')
    time.sleep(3)
    print("But you assure them that everything is fine.")
    time.sleep(3)
    print("")
    print("The seasons pass...")
    time.sleep(3)
    print("and so to do the years.")
    time.sleep(3)
    print("Your life grows and blooms,")
    time.sleep(3)
    print("and so to does your relationship.")
    time.sleep(3)
    print("And it is one beauitful, dewy afternoon,")
    time.sleep(3)
    print("that you marry that person from the date,")
    time.sleep(3)
    print("a date which is so long ago in the past.")
    time.sleep(3)
    print("You slip on your rings.")
    time.sleep(3)
    print("You go on your honeymoon.")
    time.sleep(3)
    print("And one day,")
    time.sleep(2)
    print("Many, many years later,")
    time.sleep(3)
    print("when your hair has painted itself with a frost like winter,")
    time.sleep(3)
    print("and you know comfort in routines and in slow times,")
    time.sleep(3)
    print("you look back on it all in the picture book given to you,")
    time.sleep(3)
    print("long ago by your spouse.")
    time.sleep(3)
    print("And, there...")
    time.sleep(2)
    print("yes,")
    time.sleep(2)
    print("exactly there:")
    time.sleep(2)
    print("in the corner of a photo from your wedding,")
    time.sleep(3)
    print("behind a group of smiling guests,")
    time.sleep(3)
    print("you see it.")
    time.sleep(2)
    print("You see the creature.")
    time.sleep(3)
    print("And the creature is speaking to someone...")
    time.sleep(3)
    print("someone you know...")
    time.sleep(2)
    print("The creature is speaking to your mother.")
    time.sleep(3)
    print("What ever did it say to her?")
    time.sleep(3)
    print("And how did no one notice it at your wedding?")
    time.sleep(3)
    print("That... you will have to wonder.")
    outro()

def bad_date_snacks_yes(): # rude to creature
    time.sleep(4)
    print("")
    print("Your date arrives,")
    time.sleep(2)
    print("but you are distracted by what you saw.")
    time.sleep(3)
    print("An uneasiness hovers over you,")
    time.sleep(2)
    print("and your date can tell.")
    time.sleep(3)
    print('"Thank you for the snacks,"')
    time.sleep(3)
    print('"you are so sweet," says your date,')
    time.sleep(3)
    print("squeezing your hand,")
    time.sleep(2)
    print("they can sense your distraction.")
    time.sleep(3)
    print("That evening, after your date has left,")
    time.sleep(3)
    print("you reflect on the strange creature.")
    time.sleep(3)
    print("As the weeks and months pass, you are busy with other things.")
    time.sleep(3)
    print("Your date texts a few times here and there, but you never seem to remember to reply,")
    time.sleep(3)
    print("and eventually they stop writing.")
    time.sleep(3)
    print("An online search never procures anything about the creature.")
    time.sleep(3)
    print("")
    print("Even as the years pass, nobody ever mentions anything quite like it.")
    time.sleep(3)
    print("There is simply no trace of it.")
    time.sleep(3)
    print("Even the hole it disappeared into was gone by morning.")
    time.sleep(3)
    print("You move on with your life.")
    time.sleep(3)
    print("")
    print("The days, weeks, months... and even years, roll by.")
    time.sleep(3)
    print("Sometimes, over the many decades,")
    time.sleep(3)
    print("whether it's at work,")
    time.sleep(2)
    print("an anniversary dinner") 
    time.sleep(2)
    print("or on a hike...")
    time.sleep(2)
    print("You. Hear. It.")
    time.sleep(2)
    print("Not the creature,")
    time.sleep(2)
    print("rather,")
    time.sleep(2)
    print("the faintest,")
    time.sleep(2)
    print("softest...")
    time.sleep(2)
    print("most gentle...")
    time.sleep(2)
    print("knocking.")
    outro()

def bad_date_snacks_no(): # rude to creature
    time.sleep(4)
    print("")
    print("Your date arrives,")
    time.sleep(2)
    print("but you are distracted by what you saw.")
    time.sleep(3)
    print("An uneasiness hovers over you,")
    time.sleep(2)
    print("and your date can tell.")
    time.sleep(3)
    print('"Thanks for the drinks," says your date,')
    time.sleep(3)
    print("squeezing your hand,")
    time.sleep(2)
    print("they can sense your distraction.")
    time.sleep(3)
    print('"Do you have any snacks?" they ask,')
    time.sleep(3)
    print("CREATURE.")
    time.sleep(2)
    print("CREATURE.")
    time.sleep(2)
    print("CREATURE.")
    time.sleep(2)
    print("but you are too distracted, and you don't even reply...")
    time.sleep(3)
    print("That evening, after your date has left,")
    time.sleep(3)
    print("you reflect on the strange creature.")
    time.sleep(3)
    print("As the weeks and months pass, you are busy with other things.")
    time.sleep(3)
    print("Your date texts a few times here and there, but you never seem to remember to reply,")
    time.sleep(3)
    print("and eventually they stop writing.")
    time.sleep(3)
    print("An online search never procures anything about the creature.")
    time.sleep(3)
    print("")
    print("Even as the years pass, nobody ever mentions anything quite like it.")
    time.sleep(3)
    print("There is simply no trace of it.")
    time.sleep(3)
    print("Even the hole it disappeared into was gone by morning.")
    time.sleep(3)
    print("You move on with your life.")
    print("")
    time.sleep(3)
    print("The days, weeks, months... and even years, roll by.")
    time.sleep(3)
    print("Sometimes, over the many decades,")
    time.sleep(3)
    print("whether it's at work,")
    time.sleep(2)
    print("an anniversary dinner") 
    time.sleep(2)
    print("or on a hike...")
    time.sleep(2)
    print("You. Hear. It.")
    time.sleep(2)
    print("Not the creature,")
    time.sleep(2)
    print("rather,")
    time.sleep(2)
    print("the faintest,")
    time.sleep(2)
    print("softest...")
    time.sleep(2)
    print("most gentle...")
    time.sleep(2)
    print("knocking.")
    outro()

def psycho_ending():
    time.sleep(2)
    print("")
    print("Unfortunately, they don't allow you to accompany your date to the hospital.")
    time.sleep(3)
    print("But later that evening, you hear a knocking again at your door.")
    time.sleep(3)
    print('Detectives Sauyr and Margor - please open up!"')
    time.sleep(3)
    print("You make your way to the door,")
    time.sleep(3)
    print("open it,")
    time.sleep(2)
    print("and are taken into custody.")
    time.sleep(3)
    print("The reasons don't make sense.")
    time.sleep(3)
    print("They say you strangled your date to death.")
    time.sleep(3)
    print("That their throat was severely bruised,")
    time.sleep(3)
    print("and that suspicious traces of an unknown drug were found in their stomach.")
    time.sleep(3)
    print("A drug that can only be matched to trace residues which were found on your hands,")
    time.sleep(3)
    print("and in your home...")
    time.sleep(2)
    print("The evidence for your insanity is strong:")
    time.sleep(3)
    print("The deranged story you gave in the 9-1-1 call -")
    time.sleep(3)
    print("In the court's eyes, you'll be considered to have confessed.")
    time.sleep(3)
    print("You admitted to putting the eyeball into the bowl,")
    time.sleep(3)
    print("causing your date's... incident.")
    time.sleep(2)
    print("You ask if you are being charged with murder.")
    time.sleep(3)
    print("You demand to know if your date is even alive!")
    time.sleep(3)
    print('The detectives tell you: "Manslaughter."')
    time.sleep(3)
    print("And they are also concerned, deeply,")
    time.sleep(3)
    print("regarding where you got the eyeball.")
    time.sleep(3)
    print("In your mind, flashes:")
    time.sleep(3)
    print("CREATURE. CREATURE. CREATURE.")
    time.sleep(2)
    print('"From The Creature!" you say.')
    time.sleep(3)
    print("This was never what you intended...")
    time.sleep(3)
    print("This isn't what they think!")
    time.sleep(3)
    print("This is all... WRONG.")
    time.sleep(2)
    print("AN")
    time.sleep(2)
    print("I")
    print("N")
    print("J")
    print("U")
    print("S")
    print("T")
    print("I")
    print("C")
    print("E")
    outro()

# OUTRO
def outro():
    time.sleep(5)
    print()
    print()
    print("     ######################")
    print("     |                    |")
    print("     |        The         |")
    print("     |        End         |")
    print("     |                    |")
    print("     ######################")
    print()
    print()

# MAIN FUNCTION
print()
print()
print("     ######################")
print("     |                    |")
print("     |         A          |")
print("     |        Most        |")
print("     |     Particular     |")
print("     |       Guest        |")
print("     |                    |")
print("     ######################")
print()
print()
time.sleep(10)
start_game()
